import test, { expect } from "@playwright/test";
import { loginAsAdmin } from "../helpers/auth";
import { addGeneralInfo, addUAVs, addInitialFormation, addWayointsForWaypoint_TaskConfiguration, addResponsiblePersons, deleteMission } from "../helpers/wizard_data";

test.describe.serial('TS 04 Mission Management 02 Mission Waypoint Task Configuration', () => {
  const screenshotsPath = 'tests/screenshots/TS_04_mission_management/';

  test.beforeEach(async ({ page }) => {
      await test.step('Login as admin and navigate to missions page', async () => {
        await loginAsAdmin(page);
        await expect(page).toHaveURL("/missions");
        await expect(page.getByRole('button', { name: '+ New Mission' })).toBeVisible();
        await page.getByRole('button', { name: '+ New Mission' }).click();
    });

    await test.step('Fill in mission details', async () => {
      await addGeneralInfo(page);
      await page.getByRole('button', { name: 'Next' }).click();
    });

    await test.step('Select UAVs', async () => {
      await addUAVs(page);
      await page.getByRole('button', { name: 'Next' }).click();
    });

    await test.step('Set formation type', async () => {
      await addInitialFormation(page);
      await page.getByRole('button', { name: 'Next' }).click();
    });

    await test.step('Add responsible persons', async () => {
      await addResponsiblePersons(page);
      await page.getByRole('button', { name: 'Next' }).click();
    });
  });


  test.afterEach(async ({ page }) => {
    await test.step('Delete mission', async () => {
      await deleteMission(page);
    });
  });


    test('TC 05 Create mission with only autogenerated tasks', async ({ page }) => {
        test.setTimeout(60000);
        await test.step('Add waypoints', async () => {
        await expect(page.getByText('New MissionQuitStep 5 of 8:')).toBeVisible();
        await addWayointsForWaypoint_TaskConfiguration(page);

          await page.screenshot({ path: screenshotsPath + 'TC_05/wizard_waypoints.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Detect obstacles and generate optimal route', async () => {
          await expect(page.getByText('New MissionQuitStep 6 of 8:')).toBeVisible();
          
          await page.screenshot({ path: screenshotsPath + 'TC_05/wizard_obstacles.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Verify mission details and status', async () => {
          await expect(page.getByText('New MissionQuitStep 7 of 8:')).toBeVisible();
          await expect(page.getByText('Loading weather and permits data...')).not.toBeVisible({ timeout: 30000 });
          await expect(page.getByRole('main')).toContainText('STATUSClear Airspace');

          await expect(page.locator('div').filter({ hasText: /^STATUSNo Permission Needed$/ }).first()).toBeVisible();

          await expect(page.getByText('Battery UsagePROJECTED FLIGHT')).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Operation Category' })).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Weather Conditions' })).toBeVisible();

          await page.screenshot({ path: screenshotsPath + 'TC_05/wizard_permits.png' });

          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Create mission', async () => {
          await expect(page.getByText('New MissionQuitStep 8 of 8:')).toBeVisible();

          await expect(page.getByRole('main')).toContainText('#143.706270, 16.630313🛫TakeoffAUTOTakeoff to default altitude');
          await expect(page.getByRole('main')).toContainText('MoveToPositionAUTOTarget: 43.706648, 16.630047');
          await expect(page.getByRole('main')).toContainText('#343.706373, 16.629951🛬LandAUTOLanding Point: 43.706373, 16.629951');
          await page.screenshot({ path: screenshotsPath + 'TC_05/wizard_final.png' });
          await page.getByRole('button', { name: 'Create Mission' }).click();
        });

        await test.step('Access mission overview ', async () => {
            await expect(page).toHaveURL("/missions", { timeout: 30000 });
            await page.getByRole('button', { name: 'All Missions' }).first().click();
            await page.getByRole('textbox', { name: 'Search missions by name,' }).fill('Operation Skywatch');
            await expect(page.getByRole('heading', { name: 'Operation Skywatch' })).toBeVisible();
            await page.getByText('Operation Skywatch').first().click();
        });

        await test.step('Verify mission waypoints and tasks in overview', async () => {
          await expect(page.getByRole('main')).toContainText(/#1.*43\.7062.*16\.6303.*🛫Takeoff/);
          await expect(page.getByRole('main')).toContainText(/MoveToPosition.*43\.7066.*16\.6300/);
          await expect(page.getByRole('main')).toContainText(/#3.*43\.7063.*16\.6299.*🛬Land/);
          await page.screenshot({ path: screenshotsPath + 'TC_05/mission_overview.png' });
      });
    });


      test('TC 06 Create mission with ChangeFormation task', async ({ page }) => {
        test.setTimeout(60000);
        await test.step('Add waypoints', async () => {
          await expect(page.getByText('New MissionQuitStep 5 of 8:')).toBeVisible();
          await addWayointsForWaypoint_TaskConfiguration(page);

          await page.getByRole('button', { name: '+ Add Custom Task' }).first().click();
          await page.getByRole('button', { name: '🔄 Change Formation Modify' }).click();
          await page.getByRole('button', { name: 'Grid' }).click();
          await page.getByRole('button', { name: 'Auto-Arrange Grid Formation' }).click();
          await page.getByRole('button', { name: 'Save Task' }).click();

          await expect(page.getByRole('main')).toContainText('ChangeFormation');

          await page.screenshot({ path: screenshotsPath + 'TC_06/wizard_waypoints.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Detect obstacles and generate optimal route', async () => {
          await expect(page.getByText('New MissionQuitStep 6 of 8:')).toBeVisible();
          
          await page.screenshot({ path: screenshotsPath + 'TC_06/wizard_obstacles.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Verify mission details and status', async () => {
          await expect(page.getByText('New MissionQuitStep 7 of 8:')).toBeVisible();
          await expect(page.getByText('Loading weather and permits data...')).not.toBeVisible({ timeout: 30000 });
          await expect(page.getByRole('main')).toContainText('STATUSClear Airspace');

          await expect(page.locator('div').filter({ hasText: /^STATUSNo Permission Needed$/ }).first()).toBeVisible();

          await expect(page.getByText('Battery UsagePROJECTED FLIGHT')).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Operation Category' })).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Weather Conditions' })).toBeVisible();

          await page.screenshot({ path: screenshotsPath + 'TC_06/wizard_permits.png' });

          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Create mission', async () => {
            await expect(page.getByText('New MissionQuitStep 8 of 8:')).toBeVisible();

            await expect(page.getByRole('main')).toContainText('ChangeFormation');
            await page.getByRole('button').nth(2).click();
            await expect(page.getByRole('main')).toContainText('Grid');
            await page.screenshot({ path: screenshotsPath + 'TC_06/wizard_final.png' });
            await page.getByRole('button', { name: 'Create Mission' }).click();
        });

        await test.step('Access mission overview ', async () => {
            await expect(page).toHaveURL("/missions", { timeout: 30000 });
            await page.getByRole('button', { name: 'All Missions' }).first().click();
            await page.getByRole('textbox', { name: 'Search missions by name,' }).fill('Operation Skywatch');
            await expect(page.getByRole('heading', { name: 'Operation Skywatch' })).toBeVisible();
            await page.getByText('Operation Skywatch').first().click();
        });

        await test.step('Verify mission waypoints and tasks in overview', async () => {
          await expect(page.getByRole('main')).toContainText(/#1.*43\.7062.*16\.6303.*🛫Takeoff/);
          await expect(page.getByRole('main')).toContainText(/MoveToPosition.*43\.7066.*16\.6300/);
          await expect(page.getByRole('main')).toContainText(/#3.*43\.7063.*16\.6299.*🛬Land/);
          await expect(page.getByRole('main')).toContainText('ChangeFormation');

          await page.screenshot({ path: screenshotsPath + 'TC_06/mission_overview.png' });

      });
    });

    test('TC 07 Create mission with ExecuteCommand task - no camera', async ({ page }) => {
        test.setTimeout(60000);
        await test.step('Add waypoints', async () => {
          await expect(page.getByText('New MissionQuitStep 5 of 8:')).toBeVisible();
          await addWayointsForWaypoint_TaskConfiguration(page);

          await page.getByRole('button', { name: '+ Add Custom Task' }).first().click();
          await page.getByRole('button', { name: '⚡ Execute Command Send' }).click();
          await page.getByText('Some Uav', { exact: true }).click();
          await page.locator('div').filter({ hasText: /^stringstring$/ }).first().click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('Some action');
          await page.getByRole('button', { name: 'Save Task' }).click();

          await expect(page.getByRole('main')).toContainText('ExecuteCommand');

          await page.screenshot({ path: screenshotsPath + 'TC_07/wizard_waypoints.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Detect obstacles and generate optimal route', async () => {
          await expect(page.getByText('New MissionQuitStep 6 of 8:')).toBeVisible();
          
          await page.screenshot({ path: screenshotsPath + 'TC_07/wizard_obstacles.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Verify mission details and status', async () => {
          await expect(page.getByText('New MissionQuitStep 7 of 8:')).toBeVisible();
          await expect(page.getByText('Loading weather and permits data...')).not.toBeVisible({ timeout: 30000 });
          await expect(page.getByRole('main')).toContainText('STATUSClear Airspace');

          await expect(page.locator('div').filter({ hasText: /^STATUSNo Permission Needed$/ }).first()).toBeVisible();

          await expect(page.getByText('Battery UsagePROJECTED FLIGHT')).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Operation Category' })).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Weather Conditions' })).toBeVisible();

          await page.screenshot({ path: screenshotsPath + 'TC_07/wizard_permits.png' });

          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Create mission', async () => {
            await expect(page.getByText('New MissionQuitStep 8 of 8:')).toBeVisible();

            await expect(page.getByRole('main')).toContainText('ExecuteCommand');
            await expect(page.getByRole('main')).toContainText('No Permission Needed');

            await page.screenshot({ path: screenshotsPath + 'TC_07/wizard_final.png' });
            await page.getByRole('button', { name: 'Create Mission' }).click();
        });

        await test.step('Access mission overview ', async () => {
            await expect(page).toHaveURL("/missions", { timeout: 30000 });
            await page.getByRole('button', { name: 'All Missions' }).first().click();
            await page.getByRole('textbox', { name: 'Search missions by name,' }).fill('Operation Skywatch');
            await expect(page.getByRole('heading', { name: 'Operation Skywatch' })).toBeVisible();
            await page.getByText('Operation Skywatch').first().click();
        });

        await test.step('Verify mission waypoints and tasks in overview', async () => {
          await expect(page.getByRole('main')).toContainText(/#1.*43\.7062.*16\.6303.*🛫Takeoff/);
          await expect(page.getByRole('main')).toContainText(/MoveToPosition.*43\.7066.*16\.6300/);
          await expect(page.getByRole('main')).toContainText(/#3.*43\.7063.*16\.6299.*🛬Land/);
          await expect(page.getByRole('main')).toContainText('ExecuteCommand');
          await expect(page.getByRole('main')).toContainText('No Permission Needed');

          await page.screenshot({ path: screenshotsPath + 'TC_07/wizard_overview.png' });
      });
    });

    test('TC 08 Create mission with ExecuteCommand task - camera', async ({ page }) => {
        test.setTimeout(60000);
        await test.step('Add waypoints', async () => {
          await expect(page.getByText('New MissionQuitStep 5 of 8:')).toBeVisible();
          await addWayointsForWaypoint_TaskConfiguration(page);

          await page.getByRole('button', { name: '+ Add Custom Task' }).first().click();
          await page.getByRole('button', { name: '⚡ Execute Command Send' }).click();
          await page.getByText('Some Uav', { exact: true }).click();
          await page.locator('div').filter({ hasText: /^stringstring$/ }).first().click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('CAMERA: Start Recording');
          await page.getByRole('button', { name: 'Save Task' }).click();

          await page.getByRole('button', { name: '+ Add Custom Task' }).nth(2).click();
          await page.getByRole('button', { name: '⚡ Execute Command Send' }).click();
          await page.getByText('Some Uav', { exact: true }).click();
          await page.locator('div').filter({ hasText: /^stringstring$/ }).first().click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('CAMERA: Stop Recording');
          await page.getByRole('button', { name: 'Save Task' }).click();

          await expect(page.getByRole('main')).toContainText('ExecuteCommand');

          await page.screenshot({ path: screenshotsPath + 'TC_08/wizard_waypoints.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Detect obstacles and generate optimal route', async () => {
          await expect(page.getByText('New MissionQuitStep 6 of 8:')).toBeVisible();
          
          await page.screenshot({ path: screenshotsPath + 'TC_08/wizard_obstacles.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Verify mission details and status', async () => {
          await expect(page.getByText('New MissionQuitStep 7 of 8:')).toBeVisible();
          await expect(page.getByText('Loading weather and permits data...')).not.toBeVisible({ timeout: 30000 });
          await expect(page.getByRole('main')).toContainText('STATUSClear Airspace');

          await expect(page.getByRole('main')).toContainText('STATUSPermission Required');

          await expect(page.getByText('Battery UsagePROJECTED FLIGHT')).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Operation Category' })).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Weather Conditions' })).toBeVisible();

          await page.screenshot({ path: screenshotsPath + 'TC_08/wizard_permits.png' });

          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Create mission', async () => {
            await expect(page.getByText('New MissionQuitStep 8 of 8:')).toBeVisible();

            await expect(page.getByRole('main')).toContainText('ExecuteCommand');
            await expect(page.getByRole('main')).toContainText('Permission Required');

            await page.screenshot({ path: screenshotsPath + 'TC_08/wizard_final.png' });
            await page.getByRole('button', { name: 'Create Mission' }).click();
        });

        await test.step('Access mission overview ', async () => {
            await expect(page).toHaveURL("/missions", { timeout: 30000 });
            await page.getByRole('button', { name: 'All Missions' }).first().click();
            await page.getByRole('textbox', { name: 'Search missions by name,' }).fill('Operation Skywatch');
            await expect(page.getByRole('heading', { name: 'Operation Skywatch' })).toBeVisible();
            await page.getByText('Operation Skywatch').first().click();
        });

        await test.step('Verify mission waypoints and tasks in overview', async () => {
          await expect(page.getByRole('main')).toContainText(/#1.*43\.7062.*16\.6303.*🛫Takeoff/);
          await expect(page.getByRole('main')).toContainText(/MoveToPosition.*43\.7066.*16\.6300/);
          await expect(page.getByRole('main')).toContainText(/#3.*43\.7063.*16\.6299.*🛬Land/);
          await expect(page.getByRole('main')).toContainText('ExecuteCommand');
          await expect(page.getByRole('main')).toContainText('Permission Required');

          await page.screenshot({ path: screenshotsPath + 'TC_08/wizard_overview.png' });
      });
    });

    test('TC 09 Create mission with ExecuteCommand task - camera and ChangeFormation', async ({ page }) => {
        test.setTimeout(60000);
        await test.step('Add waypoints', async () => {
          await expect(page.getByText('New MissionQuitStep 5 of 8:')).toBeVisible();
          await addWayointsForWaypoint_TaskConfiguration(page);

          await page.getByRole('button', { name: '+ Add Custom Task' }).first().click();
          await page.getByRole('button', { name: '🔄 Change Formation Modify' }).click();
          await page.getByRole('button', { name: 'Grid' }).click();
          await page.getByRole('button', { name: 'Auto-Arrange Grid Formation' }).click();
          await page.getByRole('button', { name: 'Save Task' }).click();

          await expect(page.getByRole('main')).toContainText('ChangeFormation');

          await page.getByRole('button', { name: '+ Add Custom Task' }).first().click();
          await page.getByRole('button', { name: '⚡ Execute Command Send' }).click();
          await page.getByText('Some Uav', { exact: true }).click();
          await page.locator('div').filter({ hasText: /^stringstring$/ }).first().click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('CAMERA: Start Recording');
          await page.getByRole('button', { name: 'Save Task' }).click();

          await page.getByRole('button', { name: '+ Add Custom Task' }).nth(2).click();
          await page.getByRole('button', { name: '⚡ Execute Command Send' }).click();
          await page.getByText('Some Uav', { exact: true }).click();
          await page.locator('div').filter({ hasText: /^stringstring$/ }).first().click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).click();
          await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('CAMERA: Stop Recording');
          await page.getByRole('button', { name: 'Save Task' }).click();

          await expect(page.getByRole('main')).toContainText('ExecuteCommand');

          await page.screenshot({ path: screenshotsPath + 'TC_09/wizard_waypoints.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Detect obstacles and generate optimal route', async () => {
          await expect(page.getByText('New MissionQuitStep 6 of 8:')).toBeVisible();
          
          await page.screenshot({ path: screenshotsPath + 'TC_09/wizard_obstacles.png' });
          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Verify mission details and status', async () => {
          await expect(page.getByText('New MissionQuitStep 7 of 8:')).toBeVisible();
          await expect(page.getByText('Loading weather and permits data...')).not.toBeVisible({ timeout: 30000 });
          await expect(page.getByRole('main')).toContainText('STATUSClear Airspace');

          await expect(page.getByRole('main')).toContainText('STATUSPermission Required');

          await expect(page.getByText('Battery UsagePROJECTED FLIGHT')).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Operation Category' })).toBeVisible();

          await expect(page.getByRole('heading', { name: 'Weather Conditions' })).toBeVisible();

          await page.screenshot({ path: screenshotsPath + 'TC_09/wizard_permits.png' });

          await page.getByRole('button', { name: 'Next' }).click();
        });

        await test.step('Create mission', async () => {
            await expect(page.getByText('New MissionQuitStep 8 of 8:')).toBeVisible();

            await expect(page.getByRole('main')).toContainText('ChangeFormation');
            await page.getByRole('button').nth(2).click();
            await expect(page.getByRole('main')).toContainText('Grid');

            await expect(page.getByRole('main')).toContainText('ExecuteCommand');
            await expect(page.getByRole('main')).toContainText('Permission Required');

            await page.screenshot({ path: screenshotsPath + 'TC_09/wizard_final.png' });
            await page.getByRole('button', { name: 'Create Mission' }).click();
        });

        await test.step('Access mission overview ', async () => {
            await expect(page).toHaveURL("/missions", { timeout: 30000 });
            await page.getByRole('button', { name: 'All Missions' }).first().click();
            await page.getByRole('textbox', { name: 'Search missions by name,' }).fill('Operation Skywatch');
            await expect(page.getByRole('heading', { name: 'Operation Skywatch' })).toBeVisible();
            await page.getByText('Operation Skywatch').first().click();
        });

        await test.step('Verify mission waypoints and tasks in overview', async () => {
          await expect(page.getByRole('main')).toContainText(/#1.*43\.7062.*16\.6303.*🛫Takeoff/);
          await expect(page.getByRole('main')).toContainText(/MoveToPosition.*43\.7066.*16\.6300/);
          await expect(page.getByRole('main')).toContainText(/#3.*43\.7063.*16\.6299.*🛬Land/);
          await expect(page.getByRole('main')).toContainText('ChangeFormation');
          await expect(page.getByRole('main')).toContainText('ExecuteCommand');
          await expect(page.getByRole('main')).toContainText('Permission Required');

          await page.screenshot({ path: screenshotsPath + 'TC_08/wizard_overview.png' });
      });
    });
});
 
/*
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:61117/');
  await page.getByPlaceholder('Enter latitude...').click();
  await page.getByPlaceholder('Enter latitude...').fill('43.706373');
  await page.getByPlaceholder('Enter longitude...').click();
  await page.getByPlaceholder('Enter longitude...').fill('16.629951');
  await page.getByRole('button', { name: 'Add Waypoint' }).click();
  await expect(page.getByRole('main')).toContainText('Waypoint #143.706270, 16.630313TakeOffAUTOMoveToPositionAUTO+ Add Custom Task');
  await page.getByText('Waypoint #343.706373, 16.').click();
  await expect(page.getByRole('main')).toContainText('Waypoint #343.706373, 16.629951LandAUTO+ Add Custom Task');
  await page.getByRole('button', { name: '+ Add Custom Task' }).first().click();
  await page.getByRole('button', { name: '🔄 Change Formation Modify' }).click();
  await page.getByRole('button', { name: 'Grid' }).click();
  await page.getByRole('button', { name: 'Auto-Arrange Grid Formation' }).click();
  await page.getByRole('button', { name: 'Save Task' }).click();
  await page.getByRole('button', { name: '+ Add Custom Task' }).nth(1).click();
  await page.getByRole('button', { name: '⚡ Execute Command Send' }).click();
  await page.locator('div').filter({ hasText: /^UAVSome Uav$/ }).first().click();
  await page.locator('div').filter({ hasText: /^DJI Zenmuse X7Camera$/ }).first().click();
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).click();
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('START CAMERA');
  await page.getByRole('button', { name: 'Save Task' }).click();
  await page.getByRole('button', { name: '+ Add Custom Task' }).nth(2).click();
  await page.getByRole('button', { name: '⚡ Execute Command Send' }).click();
  await page.locator('div').filter({ hasText: /^UAVSome Uav$/ }).first().click();
  await page.locator('div').filter({ hasText: /^DJI Zenmuse X7Camera$/ }).first().click();
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).click();
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('STOP CAMERA');
  await page.getByRole('button', { name: 'Save Task' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('main')).toContainText('STATUSPermission Required');
  await page.getByText('Permission Required').click();
  await expect(page.getByRole('main')).toContainText('Permission Required');
  await expect(page.getByRole('main')).toContainText('Formation 1 of 2');
  await expect(page.getByRole('button').nth(2)).toBeVisible();
  await page.getByRole('button').nth(2).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Create Mission' }).click();
  await page.getByRole('button', { name: 'Quit' }).click();
  await expect(page.getByText('#145.814999, 15.982000🛫')).toBeVisible();
  await page.getByRole('button', { name: '+ Add Custom Task' }).first().click();
  await page.getByRole('button', { name: '🔄 Change Formation Modify' }).click();
  await page.getByRole('button', { name: 'Grid' }).click();
  await page.getByRole('button', { name: 'Auto-Arrange Grid Formation' }).click();
  await page.getByRole('button', { name: 'Save Task' }).click();
  await page.getByRole('button', { name: '+ Add Custom Task' }).nth(1).click();
  await page.locator('.sc-eYEAxu').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('main')).toContainText('STATUSNo Permission Needed');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('main')).toContainText('No Permission Needed');
  await expect(page.getByRole('main')).toContainText('#143.706270, 16.630313🛫TakeoffAUTOTakeoff to default altitude🔄ChangeFormationType: Grid3 UAVs➡️MoveToPositionAUTOTarget: 43.706648, 16.630047');
  await page.getByRole('button').nth(2).click();
  await expect(page.getByRole('main')).toContainText('Grid');
  await page.getByRole('button', { name: 'All Missions' }).first().click();
  await page.getByRole('textbox', { name: 'Search missions by name,' }).fill('Test Mission Alpha');
  await page.getByText('Test Mission AlphaTuesday, February 10, 2026UpcomingTest mission for').first().click();

    await page.getByRole('button', { name: '⚡ Execute Command Send' }).click();
  await page.getByText('Some Uav', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^stringstring$/ }).first().click();
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).click();
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('N');
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('');
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('S');
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g., START_RECORDING,' }).fill('Some action');
  await page.getByRole('button', { name: 'Save Task' }).click();
});
});
*/
