// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UAV_Mission_Manager_DAL;

#nullable disable

namespace UAV_Mission_Manager_DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260112200513_AddFormationAndUAVPosition")]
    partial class AddFormationAndUAVPosition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.AdditionalEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AdditionalEquipments");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FormationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<double>("Spacing")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<int?>("WaypointId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("WaypointId");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("LocationLat")
                        .HasColumnType("float");

                    b.Property<double>("LocationLon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.MissionTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UAVId")
                        .HasColumnType("int");

                    b.Property<int>("WaypointId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UAVId");

                    b.HasIndex("WaypointId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.MissionUAV", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("UAVId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "UAVId");

                    b.HasIndex("UAVId");

                    b.ToTable("MissionUAVs");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.MissionUser", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MissionId", "Username");

                    b.HasIndex("Username");

                    b.ToTable("MissionUsers");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.UAV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("FlightTime")
                        .HasColumnType("time");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxSpeed")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("UAVs");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.UAVPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.Property<double>("RelativeX")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("RelativeY")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<int>("UAVId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.HasIndex("UAVId");

                    b.ToTable("UAVPositions");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.UAV_AdditionalEquipment", b =>
                {
                    b.Property<int>("UAVId")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalEquipmentId")
                        .HasColumnType("int");

                    b.HasKey("UAVId", "AdditionalEquipmentId");

                    b.HasIndex("AdditionalEquipmentId");

                    b.ToTable("UAV_AdditionalEquipments");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.Waypoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("float(10)");

                    b.Property<double>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("float(10)");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.ToTable("Waypoints");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSafeForFlight")
                        .HasColumnType("bit");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<int>("WeatherCode")
                        .HasColumnType("int");

                    b.Property<string>("WindDirection")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("WindSpeed")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.HasIndex("MissionId")
                        .IsUnique();

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.Formation", b =>
                {
                    b.HasOne("UAV_Mission_Manager_DAL.Entities.Mission", "Mission")
                        .WithMany("Formations")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAV_Mission_Manager_DAL.Entities.Waypoint", "Waypoint")
                        .WithMany()
                        .HasForeignKey("WaypointId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Mission");

                    b.Navigation("Waypoint");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.MissionTask", b =>
                {
                    b.HasOne("UAV_Mission_Manager_DAL.Entities.UAV", "UAV")
                        .WithMany()
                        .HasForeignKey("UAVId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UAV_Mission_Manager_DAL.Entities.Waypoint", "Waypoint")
                        .WithMany("Tasks")
                        .HasForeignKey("WaypointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UAV");

                    b.Navigation("Waypoint");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.MissionUAV", b =>
                {
                    b.HasOne("UAV_Mission_Manager_DAL.Entities.Mission", "Mission")
                        .WithMany("MissionUAVs")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAV_Mission_Manager_DAL.Entities.UAV", "UAV")
                        .WithMany("MissionUAVs")
                        .HasForeignKey("UAVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("UAV");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.MissionUser", b =>
                {
                    b.HasOne("UAV_Mission_Manager_DAL.Entities.Mission", "Mission")
                        .WithMany("MissionUsers")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAV_Mission_Manager_DAL.Entities.User", "User")
                        .WithMany("MissionUsers")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.UAVPosition", b =>
                {
                    b.HasOne("UAV_Mission_Manager_DAL.Entities.Formation", "Formation")
                        .WithMany("UAVPositions")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAV_Mission_Manager_DAL.Entities.UAV", "UAV")
                        .WithMany()
                        .HasForeignKey("UAVId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("UAV");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.UAV_AdditionalEquipment", b =>
                {
                    b.HasOne("UAV_Mission_Manager_DAL.Entities.AdditionalEquipment", "AdditionalEquipment")
                        .WithMany("UAV_AdditionalEquipments")
                        .HasForeignKey("AdditionalEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAV_Mission_Manager_DAL.Entities.UAV", "UAV")
                        .WithMany("UAV_AdditionalEquipments")
                        .HasForeignKey("UAVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalEquipment");

                    b.Navigation("UAV");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.User", b =>
                {
                    b.HasOne("UAV_Mission_Manager_DAL.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.Waypoint", b =>
                {
                    b.HasOne("UAV_Mission_Manager_DAL.Entities.Mission", "Mission")
                        .WithMany("Waypoints")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.WeatherData", b =>
                {
                    b.HasOne("UAV_Mission_Manager_DAL.Entities.Mission", "Mission")
                        .WithOne("WeatherData")
                        .HasForeignKey("UAV_Mission_Manager_DAL.Entities.WeatherData", "MissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.AdditionalEquipment", b =>
                {
                    b.Navigation("UAV_AdditionalEquipments");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.Formation", b =>
                {
                    b.Navigation("UAVPositions");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.Mission", b =>
                {
                    b.Navigation("Formations");

                    b.Navigation("MissionUAVs");

                    b.Navigation("MissionUsers");

                    b.Navigation("Waypoints");

                    b.Navigation("WeatherData");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.UAV", b =>
                {
                    b.Navigation("MissionUAVs");

                    b.Navigation("UAV_AdditionalEquipments");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.User", b =>
                {
                    b.Navigation("MissionUsers");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UAV_Mission_Manager_DAL.Entities.Waypoint", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
